import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";

import worker from "../src/index";
import { ingestRawEmail, sha256Hex } from "../src/ingest";
// Real X-Sense sample. data/ is a local-only directory (gitignored); these
// tests require the sample email to be present on the machine running them.
// "@repo-data" is aliased to <repo-root>/data in vitest.config.ts.
import realEmailText from "@repo-data/email/Your Temperature and Relative Humidity Data Export (Please Do Not Reply).eml?raw";

// Ground truth generated by the Python parser on the identical fixture:
//   uv run basement ingest-emails --raw-email-dir data/email --object-store-dir <tmp>
// (src/basement_analysis/raw_email_ingest.py). The Worker must produce the
// same content hashes, object keys, and manifest fields.
const RAW_SHA256 = "2fad5a25d4c54ca381e4e7e3e3462ec9acd204e1b28d18652e6c877660c4fe7d";
const RAW_OBJECT_KEY = `raw-emails/source=x-sense/received_date=2026-07-04/raw_sha256=${RAW_SHA256}.eml`;
const MANIFEST_OBJECT_KEY = `manifests/ingest/source=x-sense/received_date=2026-07-04/raw_sha256=${RAW_SHA256}.json`;
const EXPECTED_CSV_OBJECT_KEYS = [
  "csv/source=x-sense/export_date=2026-07-03/attachment_sha256=a4ae92685fd8618a341c8b479fb8c3573e71d7875740af29fb92ee052596d29a/Thermo-hygrometer_Export_Data_20260703.csv",
  "csv/source=x-sense/export_date=2026-07-03/attachment_sha256=770af430dac2e15b1225e84ec021322c817fef489b7f3111174463e50fe411b9/Thermo-hygrometer_2_Export_Data_20260703.csv",
  "csv/source=x-sense/export_date=2026-07-03/attachment_sha256=9eef1608890e864667564b3881b05f0433718fab660a3ad835f13ac7cc7c9c9a/Thermo-hygrometer_3_Export_Data_20260703.csv",
];

const realEmailBytes = new TextEncoder().encode(realEmailText);

function emailMessage(rawBytes: Uint8Array): ForwardableEmailMessage {
  return {
    from: "support@x-sense.com",
    to: "basement-ingest@robjhornby.com",
    headers: new Headers(),
    raw: new Response(rawBytes).body as ReadableStream,
    rawSize: rawBytes.byteLength,
    setReject(): void {},
    async forward(): Promise<void> {},
    async reply(): Promise<void> {},
  } as unknown as ForwardableEmailMessage;
}

function syntheticEmail(subject: string, csvBodies: Record<string, string>): Uint8Array {
  const boundary = "test-boundary";
  const lines = [
    "From: someone@example.test",
    "To: basement-ingest@robjhornby.com",
    `Subject: ${subject}`,
    "Message-ID: <synthetic-test@example.test>",
    "Date: Sat, 4 Jul 2026 09:00:00 +0000",
    "MIME-Version: 1.0",
    `Content-Type: multipart/mixed; boundary="${boundary}"`,
    "",
    `--${boundary}`,
    "Content-Type: text/plain",
    "",
    "Daily export attached.",
  ];
  for (const [filename, body] of Object.entries(csvBodies)) {
    lines.push(
      `--${boundary}`,
      "Content-Type: application/octet-stream",
      `Content-Disposition: attachment; filename="${filename}"`,
      "",
      ...body.split("\n"),
    );
  }
  lines.push(`--${boundary}--`, "");
  return new TextEncoder().encode(lines.join("\r\n"));
}

async function listKeys(prefix: string): Promise<string[]> {
  const listing = await env.PIPELINE_BUCKET.list({ prefix });
  return listing.objects.map((object) => object.key);
}

describe("accept path with the real X-Sense sample", () => {
  it("computes the same raw hash as the Python parser", async () => {
    expect(await sha256Hex(realEmailBytes)).toBe(RAW_SHA256);
  });

  it("writes raw .eml, three CSVs, and an ingest manifest with Python-identical keys", async () => {
    const outcome = await ingestRawEmail(realEmailBytes, env.PIPELINE_BUCKET);

    expect(outcome.status).toBe("accepted");
    expect(outcome.raw_object_key).toBe(RAW_OBJECT_KEY);
    expect(outcome.manifest_object_key).toBe(MANIFEST_OBJECT_KEY);
    expect(outcome.attachments.map((attachment) => attachment.csv_object_key)).toEqual(
      EXPECTED_CSV_OBJECT_KEYS,
    );
    expect(outcome.attachments.map((attachment) => attachment.status)).toEqual([
      "extracted",
      "extracted",
      "extracted",
    ]);
    expect(outcome.attachments.map((attachment) => attachment.row_count)).toEqual([
      1440, 1440, 1440,
    ]);

    const rawObject = await env.PIPELINE_BUCKET.get(RAW_OBJECT_KEY);
    expect(rawObject).not.toBeNull();
    expect(new Uint8Array(await rawObject!.arrayBuffer())).toEqual(realEmailBytes);

    for (const csvObjectKey of EXPECTED_CSV_OBJECT_KEYS) {
      expect(await env.PIPELINE_BUCKET.head(csvObjectKey)).not.toBeNull();
    }

    const manifestObject = await env.PIPELINE_BUCKET.get(MANIFEST_OBJECT_KEY);
    expect(manifestObject).not.toBeNull();
    const manifest = (await manifestObject!.json()) as Record<string, unknown>;
    expect(manifest.status).toBe("accepted");
    expect(manifest.source).toBe("x-sense");
    expect(manifest.received_date).toBe("2026-07-04");
    expect(manifest.raw_sha256).toBe(RAW_SHA256);
    expect(manifest.raw_object_key).toBe(RAW_OBJECT_KEY);
    expect(manifest.parser_version).toBe("basement_email_ingest_worker.v1");
    const headers = manifest.headers as Record<string, string>;
    expect(headers.message_id).toBe(
      "<0100019f2ce075c7-2f2733de-4929-4d39-b39b-d19ef5537852-000000@email.amazonses.com>",
    );
    expect(headers.from).toContain("support@x-sense.com");
    const attachments = manifest.attachments as Array<Record<string, unknown>>;
    expect(attachments).toHaveLength(3);
    expect(attachments[0].filename).toBe("Thermo-hygrometer_Export Data_20260703.csv");
    expect(attachments[0].csv_object_key).toBe(EXPECTED_CSV_OBJECT_KEYS[0]);
  });

  it("ingests through the Worker email() handler", async () => {
    await worker.email(emailMessage(realEmailBytes), env);

    expect(await env.PIPELINE_BUCKET.head(RAW_OBJECT_KEY)).not.toBeNull();
    expect(await env.PIPELINE_BUCKET.head(MANIFEST_OBJECT_KEY)).not.toBeNull();
    expect(await listKeys("csv/")).toEqual([...EXPECTED_CSV_OBJECT_KEYS].sort());
  });

  it("treats redelivery of identical raw bytes as a no-op duplicate", async () => {
    const first = await ingestRawEmail(realEmailBytes, env.PIPELINE_BUCKET);
    const second = await ingestRawEmail(realEmailBytes, env.PIPELINE_BUCKET);

    expect(first.status).toBe("accepted");
    expect(second.status).toBe("duplicate_raw_sha256");
    expect(second.attachments).toEqual([]);
    expect(await listKeys("manifests/")).toEqual([MANIFEST_OBJECT_KEY]);
  });

  it("dedupes identical CSV content from a distinct raw email (e.g. a forward)", async () => {
    const forwardedBytes = new TextEncoder().encode(
      `X-Forwarded-Test: gmail-forward\r\n${realEmailText}`,
    );
    const original = await ingestRawEmail(realEmailBytes, env.PIPELINE_BUCKET);
    const forwarded = await ingestRawEmail(forwardedBytes, env.PIPELINE_BUCKET);

    expect(original.status).toBe("accepted");
    expect(forwarded.status).toBe("accepted");
    expect(forwarded.raw_sha256).not.toBe(original.raw_sha256);
    expect(forwarded.attachments.map((attachment) => attachment.status)).toEqual([
      "duplicate_content_hash",
      "duplicate_content_hash",
      "duplicate_content_hash",
    ]);
    expect(forwarded.attachments.map((attachment) => attachment.csv_object_key)).toEqual([
      null,
      null,
      null,
    ]);
    expect(await listKeys("csv/")).toEqual([...EXPECTED_CSV_OBJECT_KEYS].sort());
    expect((await listKeys("manifests/ingest/")).length).toBe(2);
  });
});

describe("reject paths", () => {
  it("stores raw evidence plus a rejection manifest for a non-X-Sense subject", async () => {
    const rawBytes = syntheticEmail("Weekly newsletter", {});
    const outcome = await ingestRawEmail(rawBytes, env.PIPELINE_BUCKET);

    expect(outcome.status).toBe("subject_mismatch");
    expect(outcome.validation_errors.join("\n")).toContain(
      "subject does not match accepted X-Sense pattern",
    );
    expect(await env.PIPELINE_BUCKET.head(outcome.raw_object_key)).not.toBeNull();
    expect(outcome.manifest_object_key).toBe(
      `manifests/rejections/source=x-sense/received_date=2026-07-04/raw_sha256=${outcome.raw_sha256}.json`,
    );

    const manifestObject = await env.PIPELINE_BUCKET.get(outcome.manifest_object_key);
    expect(manifestObject).not.toBeNull();
    const manifest = (await manifestObject!.json()) as Record<string, unknown>;
    expect(manifest.status).toBe("subject_mismatch");
    expect(manifest.validation_errors).toBeInstanceOf(Array);
    expect(await listKeys("manifests/ingest/")).toEqual([]);
    expect(await listKeys("csv/")).toEqual([]);
  });

  it("rejects an X-Sense-looking email whose CSV attachment misses required columns", async () => {
    const rawBytes = syntheticEmail(
      "Your Temperature and Relative Humidity Data Export (Please Do Not Reply)",
      {
        "sensor-a.csv": "Time,Temperature_Celsius\n2026/07/03 00:00,18.5",
        "sensor-b.csv": "Time,Temperature_Celsius\n2026/07/03 00:00,18.6",
        "sensor-c.csv": "Time,Temperature_Celsius\n2026/07/03 00:00,18.7",
      },
    );
    const outcome = await ingestRawEmail(rawBytes, env.PIPELINE_BUCKET);

    expect(outcome.status).toBe("invalid_csv_attachments");
    expect(outcome.validation_errors.join("\n")).toContain(
      "missing required columns: Relative Humidity_Percent",
    );
    expect(outcome.attachments.map((attachment) => attachment.status)).toEqual([
      "invalid_csv",
      "invalid_csv",
      "invalid_csv",
    ]);
    expect(await listKeys("csv/")).toEqual([]);
    expect(await listKeys("manifests/rejections/")).toEqual([outcome.manifest_object_key]);
  });

  it("rejects an unexpected CSV attachment count without extracting", async () => {
    const rawBytes = syntheticEmail(
      "Your Temperature and Relative Humidity Data Export (Please Do Not Reply)",
      {
        "only-sensor.csv":
          "Time,Temperature_Celsius,Relative Humidity_Percent\n2026/07/03 00:00,18.5,67.2",
      },
    );
    const outcome = await ingestRawEmail(rawBytes, env.PIPELINE_BUCKET);

    expect(outcome.status).toBe("unexpected_csv_attachment_count");
    expect(outcome.validation_errors.join("\n")).toContain("expected 3 CSV attachments, found 1");
    expect(outcome.attachments.map((attachment) => attachment.status)).toEqual(["skipped"]);
    expect(await listKeys("csv/")).toEqual([]);
    expect(await listKeys("manifests/rejections/")).toEqual([outcome.manifest_object_key]);
  });
});
